(()=>{
const css=document.createElement('style');css.textContent=`body{padding-bottom:78px!important}.appnav{position:fixed;left:0;right:0;bottom:0;z-index:45;height:70px;background:#fff;border-top:1px solid #d8dce2;display:flex;overflow-x:auto;box-shadow:0 -3px 14px #0001;padding-bottom:env(safe-area-inset-bottom)}.appnav button{min-width:72px;flex:1;font-size:10.5px;font-weight:700;color:#6b7480;padding:7px 3px}.appnav button b{display:block;font-size:21px;line-height:26px}.appnav button.on{color:#c1272d}.apphome{padding:14px 12px}.apphello{background:linear-gradient(135deg,#c1272d,#8f1c21);color:white;border-radius:16px;padding:20px;margin-bottom:14px}.apphello h2{font-size:22px;margin-bottom:5px}.cards{display:grid;grid-template-columns:1fr 1fr;gap:10px}.catcard{background:#fff;border:1px solid #dfe2e6;border-radius:14px;padding:18px 12px;text-align:left;box-shadow:0 4px 12px #0000000a}.catcard b{display:block;font-size:27px;margin-bottom:8px}.catcard strong{font-size:15px}.catcard small{display:block;color:#7a828d;margin-top:4px}.simplepage{padding:14px 12px}.simplepage h2{font-size:22px;margin:5px 0 14px}.emptycard{background:#fff;border:1px solid #dfe2e6;border-radius:14px;padding:22px 16px;line-height:1.7;color:#626b76}.boardhead{padding:10px 12px;background:#fff;border-bottom:1px solid #ddd;display:flex;gap:8px}.boardhead button{background:#c1272d;color:#fff;padding:9px 12px;border-radius:9px;font-weight:700}`;document.head.appendChild(css);
const main=document.querySelector('main'),header=document.querySelector('header');if(!main||!header)return;
const original=main.innerHTML;let current='home';
const pages=[['home','🏠','홈'],['notice','📢','공지사항'],['volume','🚚','오늘물량'],['radio','📻','무전'],['board','📊','현황판'],['money','💰','가계부'],['rules','📘','회칙']];
const nav=document.createElement('nav');nav.className='appnav';nav.innerHTML=pages.map(x=>`<button data-p="${x[0]}"><b>${x[1]}</b>${x[2]}</button>`).join('');document.body.appendChild(nav);
function empty(title,icon,desc){main.innerHTML=`<section class="simplepage"><h2>${icon} ${title}</h2><div class="emptycard">${desc}<br><br>이 카테고리는 다음 단계에서 Firebase 실시간 저장 기능과 관리자 입력 기능을 연결할 수 있습니다.</div></section>`}
function show(p){current=p;nav.querySelectorAll('button').forEach(b=>b.classList.toggle('on',b.dataset.p===p));header.style.display=p==='board'?'block':'none';if(p==='home'){main.innerHTML=`<section class="apphome"><div class="apphello"><h2>대왕레미콘</h2><div>업무를 한 곳에서 확인하세요.</div></div><div class="cards">${pages.slice(1).map(x=>`<button class="catcard" data-go="${x[0]}"><b>${x[1]}</b><strong>${x[2]}</strong><small>${x[0]==='radio'?'실시간 무전 연결':x[0]==='board'?'차량운행 현황 확인':'내용 확인 및 관리'}</small></button>`).join('')}</div></section>`;main.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));return}if(p==='board'){render();return}if(p==='radio'){main.innerHTML='<section class="simplepage"><h2>📻 무전</h2><div class="emptycard">기사 선택과 실시간 무전방을 관리합니다.</div><div class="boardhead"><button id="openRadioApp">무전방 열기</button></div></section>';document.querySelector('#openRadioApp').onclick=()=>document.querySelector('#radioBtn').click();return}if(p==='notice')empty('공지사항','📢','회사 공지와 전달사항을 확인하는 공간입니다.');if(p==='volume')empty('오늘물량','🚚','오늘 예정 물량과 배차 정보를 확인하는 공간입니다.');if(p==='money')empty('가계부','💰','수입·지출 및 회비 내역을 관리하는 공간입니다.');if(p==='rules')empty('회칙','📘','대왕레미콘 회칙과 운영 규정을 확인하는 공간입니다.')}
nav.onclick=e=>{const b=e.target.closest('button[data-p]');if(b)show(b.dataset.p)};show('home');
})();